### ISSUE TITLE
Consider expanding the coverage of tags in the report "interest" flags

### ISSUE THREAD

**Issue by jmtd** [shipilev/jdk-backports-monitor#4]
Currently your (excellent) reports include a column with characters representing if the issue has been labelled with an "interest" label, e.g. label redhat-interest => "R" in the column. Would you consider accepting patches to expand this to cover other potentially useful labels?

For the reporting/analysis I do, I try to work entirely from the parity reports you generate. The information I need to fetch separately from JBS is (currently) entirely labels.

The one that would be immediately useful to me if available in the parity reports is "jdk11u-jvmci-defer", but there may be others. I'm hesitant to enumerate them all in case we change it all again…

**Comment by shipilev** [comment]
Sure, submit PRs!
