### ISSUE TITLE
exclusion of 'jdk8u-fix-no' bugs from 8u parity reports not working

### ISSUE THREAD

**Issue by jmtd** [shipilev/jdk-backports-monitor#8]
The following issue shows up in the latest 8u parity reports:
https://bugs.openjdk.java.net/browse/JDK-8215281
It is labelled 'jdk8u-fix-no'

 there seems to be some handling of u-fix-no labels in the monitor already: https://github.com/shipilev/jdk-backports-monitor/blob/8986254874d553ba50b9ac60eca23d18d62d3975/src/main/java/org/openjdk/backports/report/model/IssueModel.java#L153

**Comment by shipilev** [comment]
This should be fixed by https://github.com/shipilev/jdk-backports-monitor/commit/c8274e17e6d827611f8982b7100309a9971aea67. It would take some time to show up in generated parity reports, as I took some servers down for maintenance, but you should be able to do `--parity 8` report yourself.

**Comment by shipilev** [comment]
Look [here](https://builds.shipilev.net/backports-monitor/parity-8.html), JDK-8215281 is now properly reported as "OpenJDK Rejected".
