### ISSUE TITLE
parity reports should exclude "jdkXu-na" tagged issues

### ISSUE THREAD

**Issue by jmtd** [shipilev/jdk-backports-monitor#9]
https://bugs.openjdk.java.net/browse/JDK-8268214 is an example of an issue tagged `jdk11u-na` which shows up in the latest `parity_11u.txt`. It would be great if they were excluded (or otherwise categorised/filtered) in the parity reports. (I think this tag might only have been invented a few days ago)

**Comment by shipilev** [comment]
Should be fixed with https://github.com/shipilev/jdk-backports-monitor/commit/af8ae3372e85b7025068b884fab128f773b32013.
